from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_DIR = ROOT / "artifacts" / "factor_mlp"


def format_float(value: float) -> str:
    return f"{value:.9g}"


def error_report(name: str, lhs: np.ndarray, rhs: np.ndarray) -> list[str]:
    if lhs.shape != rhs.shape:
        raise AssertionError(f"{name} shape mismatch: {lhs.shape} vs {rhs.shape}")

    diff = lhs.astype(np.float64) - rhs.astype(np.float64)
    abs_error = np.abs(diff)
    rel_error = abs_error / np.maximum(np.abs(rhs.astype(np.float64)), 1e-12)
    flat_index = int(abs_error.argmax()) if abs_error.size else 0
    index = np.unravel_index(flat_index, abs_error.shape) if abs_error.size else ()

    lines = [
        f"[{name}]",
        f"shape={lhs.shape}",
        f"max_abs_error={format_float(float(abs_error.max() if abs_error.size else 0.0))}",
        f"mean_abs_error={format_float(float(abs_error.mean() if abs_error.size else 0.0))}",
        f"rmse={format_float(float(np.sqrt(np.mean(diff * diff)) if diff.size else 0.0))}",
        f"max_rel_error={format_float(float(rel_error.max() if rel_error.size else 0.0))}",
        f"mean_rel_error={format_float(float(rel_error.mean() if rel_error.size else 0.0))}",
        f"max_abs_error_index={index}",
    ]
    if abs_error.size:
        lines.extend(
            [
                f"lhs_at_max={format_float(float(lhs[index]))}",
                f"rhs_at_max={format_float(float(rhs[index]))}",
            ]
        )
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare Python .pt output against C++ dlopen .so output.")
    parser.add_argument(
        "--python-output",
        type=Path,
        default=ARTIFACT_DIR / "python_pt_output.npy",
        help="Output produced by tools/run_python_pt_reference.py.",
    )
    parser.add_argument(
        "--cpp-output",
        type=Path,
        default=ARTIFACT_DIR / "cpp_dlopen_output.npy",
        help="Output produced by tools/run_dlopen_model.cpp.",
    )
    parser.add_argument(
        "--expected-output",
        type=Path,
        default=ARTIFACT_DIR / "expected_output.npy",
        help="Optional original expected_output.npy generated by create_factor_mlp.py.",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=ARTIFACT_DIR / "python_vs_cpp_report.txt",
        help="Text report path.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=1e-5,
        help="Maximum allowed absolute error between Python and C++ outputs.",
    )
    args = parser.parse_args()

    python_output = np.load(args.python_output).astype(np.float32, copy=False)
    cpp_output = np.load(args.cpp_output).astype(np.float32, copy=False)

    lines: list[str] = []
    lines.extend(error_report("python_pt_vs_cpp_dlopen", python_output, cpp_output))

    if args.expected_output.exists():
        expected_output = np.load(args.expected_output).astype(np.float32, copy=False)
        lines.append("")
        lines.extend(error_report("python_pt_vs_expected_output", python_output, expected_output))
        lines.append("")
        lines.extend(error_report("cpp_dlopen_vs_expected_output", cpp_output, expected_output))

    report = "\n".join(lines) + "\n"
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(report, encoding="utf-8")
    print(report, end="")
    print(f"report={args.report}")

    abs_error = np.abs(python_output.astype(np.float64) - cpp_output.astype(np.float64))
    max_abs_error = float(abs_error.max() if abs_error.size else 0.0)
    if max_abs_error > args.threshold:
        raise AssertionError(
            f"python_pt_vs_cpp_dlopen max_abs_error exceeds threshold "
            f"{args.threshold}: {max_abs_error}"
        )


if __name__ == "__main__":
    main()
